export { default as PBody } from './PBody.vue'
export { default as PFooter } from './PFooter.vue'
export { default as PHeader } from './PHeader.vue'
export { default as PHeaderButton } from './PHeaderButton.vue'
export { default as PScaffold } from './PScaffold.vue'
